### ISSUE TITLE
Feat: Beitraege in Gliederung

### ISSUE THREAD

**Issue by tina-e** [UniRegensburg/basisdokument#104]
Als Nutzer:in möchte ich, dass Beiträge (mit einem optionalen Titel) in der Gliederung gelistet werden, um eine zweite Gliederungsebene abzubilden.

**Akzeptanzkriterien**
- [x] ~~Optionaler Titel für Beiträge~~
- [x] Beiträge in Gliederung
- [x] hover state um click-to-view anzuzeigen
- [x] Ein-/Ausklappen der Beiträge in Gliederung

**Comment by tina-e** [comment]
Titel diskutieren:
- Wo im Beitrag anzeigen?
- Überhaupt sinnvoll?
- Wie sortieren dann?

**Comment by JuliaSageder** [comment]
siehe dazu auch Issue #11

**Comment by JuliaSageder** [comment]
Zusätzliche Funktions-Anforderung:
- [ ] Button "alles einklappen"
- [ ] Button "alles ausklappen"

**Comment by JuliaSageder** [comment]
Kleiner Fehler: Bezugnehmende Beiträge tauchen noch nicht auf
