### ISSUE TITLE
Feat: Erweiterung Beitraege-Popup

### ISSUE THREAD

**Issue by JuliaSageder** [UniRegensburg/basisdokument#107]
**Beschreibung des Features**
Es wird diskutiert, ob das Beiträge-Popup (zwei bezugnehmende Beiträge nebeneinander, siehe Issue #36 ) so erweitert werden soll, dass der gesamte Verlauf einer Bezugnahmen-Kette angezeigt wird. Denkbar wäre hier eine horizontale Scrollbar.

**Akzeptanzkriterien**
- [ ] Inhaltliche Erweiterung des Popups um alle bezugnehmenden Beiträge (nicht nur der aktuelle + die Bezugnahme)
- [ ] Übersichtliche UI-Darstellung (z.B. horizontale Scrollbar - Alternativen denkbar)

**Comment by tina-e** [comment]
Direkte Bezüge der beiden im Popup dargestellten Beiträge werden ebenfalls gelistet (wenn vorhanden)
![image](https://github.com/UniRegensburg/basisdokument/assets/53038141/ecfbe292-d384-4950-a766-0739347d4cd0)

Ein erster Vorschlag, gerne am Mittwoch diskutieren.
