### ISSUE TITLE
Feat: Bilder/PDFs einfuegen

### ISSUE THREAD

**Issue by tina-e** [UniRegensburg/basisdokument#113]
Als Nutzer:in möchte ich Bilder als Anlage hochgeladen können, um meine Argumentation mit Bildern zu unterstützen. 

- [x] Upload im Beweisbereich
- [x] Button zum Anzeigen des Bildes
- [x] Popup zum Anzeigen des Bildes
- [x] Error, wenn anderes File als Bild hochgeladen
- [x] Abklären: mit Bild => zwingend als Anlage?

siehe Kommentar unten:
- [x]  Bilder nicht direkt ins PDF sondern mit richtiger Benennung (Anlage X + Bezeichnung) mit herunterladen, bestenfalls in zwei eigenen Ordnern (Anlagen Kläger, Anlagen Beklagter)
- [ ]  Option nur neueste/alle Bilder/Anhänge mit herunterladen
- [x]  dasselbe wie für Bilder soll für PDF-Anhänge möglich sein
- [x]  Fehler in der Nummerierung fixen! (K1 - K1 bei Bildern) (bisher nicht reproduzierbar!)
- [x] Bilder(/PDF)-Anhänge in der Sidebar kennzeichnen? (z.B. Icon? Klickbar wie im Beitrag?)
- [x] Filter in der Sidebar nach Anhängen mit Bildern/PDF? 
- [x] Fehler gefunden: Bild kann u.U. auch hinzugefügt werden, wenn noch keine Datei hochgeladen ist

**Comment by tina-e** [comment]
- [ ] Bilder ins PDF

**Comment by JuliaSageder** [comment]
Update zu den Anforderungen (JourFixe):
- [ ]  Bilder nicht direkt ins PDF sondern mit richtiger Benennung (Anlage X + Bezeichnung) mit herunterladen, bestenfalls in zwei eigenen Ordnern (Anlagen Kläger, Anlagen Beklagter)
- [ ] Option nur neueste/alle Bilder/Anhänge mit herunterladen
- [ ] dasselbe wie für Bilder soll für PDF-Anhänge möglich sein

- [ ] Fehler in der Nummerierung fixen! (K1 - K1 bei Bildern)

**Comment by JuliaSageder** [comment]
Weitere Anmerkungen:

- [ ] Bilder(/PDF)-Anhänge in der Sidebar kennzeichnen? (z.B. Icon? Klickbar wie im Beitrag?)
- [ ] Filter in der Sidebar nach Anhängen mit Bildern/PDF?

**Comment by JuliaSageder** [comment]
- [ ] Fehler gefunden: Bild kann u.U. auch hinzugefügt werden, wenn noch keine Datei hochgeladen ist

**Comment by JuliaSageder** [comment]
- [ ] max. Volumen von beiden Parteien auf 40 MB begrenzen
- [ ] Fortschrittsbalken mit Anzeige wie viel von den 40 MB schon verbraucht ist
