### ISSUE TITLE
Bugfix: Fehlende Verweise in der Beweissidebar

### ISSUE THREAD

**Issue by JuliaSageder** [UniRegensburg/basisdokument#119]
**Describe the bug**
In der Beweissidebar fehlen Verweise auf Beiträge in Beweisen: Siehe Screenshot -> Auf Zeuge Klaus Franz wird mehreren Beiträgen verwiesen, es ist aber nur auf den Originalbeitrag verwiesen.

**Expected behavior**
Alle Beiträge die einen Beweis aufführen sollten als Verweis in diesem Beweis in der Beweissidebar auftauchen.

**Screenshots**
![FEHLER_Beweissidebar](https://github.com/UniRegensburg/basisdokument/assets/126691623/c809cf9c-6671-4c4a-b395-2b49764b6407)

**Comment by tina-e** [comment]
seems to be fixed with #113
