### ISSUE TITLE
Feat: Signatur Erweiterung

### ISSUE THREAD

**Issue by JuliaSageder** [UniRegensburg/basisdokument#125]
**Beschreibung des Features**
Die Signatur soll durch ein Dropdown um zusätzliche dienstrechtlich wichtige Bezeichnungen von Richter:innen erweitert werden. Die Inhalte für das Dropdown wurden von Mitgliedern der Projektgruppe zur Verfügung gestellt:

- Richterin
- Richter
- Richterin am Landgericht
- Richter am Landgericht
- Vorsitzende Richterin am Landgericht
- Vorsitzender Richter am Landgericht
- Vizepräsidentin des Landesgerichts
- Vizepräsident des Landgerichts
- Präsidentin des Landgerichts
- Präsident des Landgerichts

**Akzeptanzkriterien**
- [ ] optionales Dropdown mit Auswahlmöglichkeiten bei der Signatur integrieren
- [ ] Signatur im PDF nach Auswahl anpassen

**Comment by tina-e** [comment]
![image](https://github.com/UniRegensburg/basisdokument/assets/53038141/14ea67bf-8008-477e-b25c-37342674a882)
Auswahl bei Menü links oben ergänzt (zusätzliches Property bei IUser).
Zu besprechen: Signaturänderung bei Download?

**Comment by tina-e** [comment]
- [ ] Signatur nur bei Export
- [ ] #135
