### ISSUE TITLE
Feat: Beitrag splitten/Zitieren

### ISSUE THREAD

**Issue by JuliaSageder** [UniRegensburg/basisdokument#14]
**Beschreibung des Features**
Soll es möglich sein die Beiträge im Nachhinein aufsplitten zu können oder wäre eine andere erweiterte Möglichkeit der Bezugnahme sinnvoller?
Dies muss noch weiter diskutiert/in einem Nutzertest mögliche Ansätze in irgendeiner Form getestet werden.

Eine Alternative die jetzt umgesetzt werden soll: Möglichkeit auf konkretere Bezugnahme ("Zitat") in bezugnehmenden Beiträgen. Das heißt, bei der Markierung von Text in Beiträgen soll daneben ein Button erscheinen, mit dem ein neuer bezugnehmender Beitrag erstellt wird, der den markierten Text als Zitat für die Bezugnahme im Beitrag voranstellt.

**Akzeptanzkriterien**
- [ ] neue Interaktion erstellen: neben markierten Text Button für Bezugnahme
- [x] markierten Text abfangen und in einem neuen Bereich dem neuen bezugnehmenden Beitrag voranstellen
- [x] Zitate im PDF anzeigen

**Comment by kindOfCurly** [comment]
Zitieren von Textausschnitten in bezugnehmenden Beiträgen umgesetzt.

Merged in #162
