### ISSUE TITLE
Feat: Verschiebbare Popups

### ISSUE THREAD

**Issue by JuliaSageder** [UniRegensburg/basisdokument#143]
**Beschreibung des Features**
Um die Daten zu sehen, die hinter den Popups sind, soll es möglich sein diese wie Fenster auf einem Desktop verschieben zu können. Dabei wäre wichtig, dass sie keine Bildschirmgrenze überschreiten können und das Draggen nur über einen Button/Bereich und nicht für das gesamte Popup funktioniert.

**Akzeptanzkriterien**
- [x] Button/Breich hinzufügen, der klar als Drag-Möglichkeit vom Nutzer erkannt wird
- [ ] Berechnen/Feststellen wo die vier Eckpunkte des Popups sind und das Dragverhalten auf die Boundaries des Screens beschränken
- [x] Rücksetzmöglichkeit auf den Originalplatz, z.B. durch einen Button oder Snap-Bereich

**Comment by tina-e** [comment]
Erstmal für EvidencePopup umgesetzt.   

![image](https://github.com/UniRegensburg/basisdokument/assets/53038141/5ff7b921-4229-4263-a1bd-7cc3b8e63837)

- [x] Verschieben des Popups durch Draggen des Move-Icons
- [x] Popup kann nur so verschoben werden, dass das Move-Icon immer innerhalb des Screens ist 
- [x] Reset der Position onDoubleClick auf das Move-Icon
- [x] Design absegnen
- [ ] Für alle anderen Popups übernehmen; dafür zunächst: #151

**Comment by kindOfCurly** [comment]
Einschränkung: Popup kann nur so verschoben werden, dass das Move-Icon immer innerhalb des Screens ist.

Merged in #162
