### ISSUE TITLE
Bugfix: Beweise tauchen mehrfach auf in der PDF-Beweisliste

### ISSUE THREAD

**Issue by JuliaSageder** [UniRegensburg/basisdokument#147]
**Describe the bug**
In der PDF-Beweisliste tauchen Beweise vielfach auf, obwohl sie nur einmal vorkommen sollten.

**To Reproduce**
1. Beweise in einem Basisdokument hinzufügen
2. Beim Herunterladen auf "Zusätzlich eine Liste aller Beweise in einer eigenen PDF herunterladen" klicken
3. PDF-Beweisliste öffnen
4. Beweise sind mehrfach in der Liste

**Expected behavior**
Jeder Beweis sollte nur einmal in der Liste auftauchen.

**Screenshots**
![image](https://github.com/UniRegensburg/basisdokument/assets/126691623/4f64f713-ed17-4f1b-bcec-152fc8801441)

**Comment by kindOfCurly** [comment]
fixed and merged in #162
