### ISSUE TITLE
Bugfix: Fehler bei Nummerierung und Beweisen

### ISSUE THREAD

**Issue by JuliaSageder** [UniRegensburg/basisdokument#148]
**Describe the bug**
Beweise tauchen mehrfach auf und es entstehen Fehler bei der Nummerierung. Möglicherweise entstehen diese Fehler, wenn Beiträge nicht gleich gespeichert werden, sondern mehrere parallel ohne Speichern geöffnet sind.

**To Reproduce**
1. Mehrere Beiträge hinzufügen ohne sie zu speichern
2. Beweise anlegen und manche Beiträge speichern
3. Neue Beiträge anlegen und dort Beweise hinzufügen (auch aus der Vorschlagsliste)
4. Nummerierung und Beweise sind durcheinander

**Expected behavior**
Beweise und Nummerierung sollten nachvollziehbar vergeben und konsistent sein.

**Comment by kindOfCurly** [comment]
Möglicher Fix: Es kann jetzt immer nur noch ein Beitrag gleichzeitig bearbeitet werden. (merged in #162)

Bug nicht mehr reproduzierbar.
