### ISSUE TITLE
Feat: Rubrum Anhang

### ISSUE THREAD

**Issue by JuliaSageder** [UniRegensburg/basisdokument#153]
**Beschreibung des Features**
Zusätzlich zu der Möglichkeit Anhänge in Form von PDFs und TIFFs in Beiträgen zu speichern soll es möglich sein, diese auch für das Rubrum hinzuzufügen.

**Akzeptanzkriterien**
- [x] Anhang Option zu Rubren hinzufügen
- [x] Variation des Beweis-Popups für Rubren-Anhänge implementieren
- [x] Anhang in die Datenmenge einkalkulieren, aber sonst nicht mit Beweisen verknüpfen

**Comment by kindOfCurly** [comment]
merged in #162
