### ISSUE TITLE
Feat: print

### ISSUE THREAD

**Issue by JuliaSageder** [UniRegensburg/basisdokument#21]
**Beschreibung des Features**
Es soll eine readonly Ansicht für Mandanten (siehe Issue #34 ), bzw. (als vorläufige Zwischenlösung) eine Möglichkeit geben das Basisdokument in seiner Browseransicht ausdrucken zu können - zusätzlich zu der visuell besser gegliederten PDF-Version (vgl. Issue #15 )

**Akzeptanzkriterien**
- [ ] Zwischenlösung: Printversion des Basisdokuments optimieren (aktuell wird nur 1 Seite/die Ansicht ausgedruckt)
- [x] einen neuen User-Typ integrieren der nur readonly-Rechte besitzt (siehe Issue #34 !)

**Comment by tina-e** [comment]
Aufgesplittet. Teil B readonly jetzt in #34

**Comment by JuliaSageder** [comment]
Issue wurde für die letzten Anforderungen ausgeschlossen, ist aber für eine mögliche spätere Version des Basisdokuments relevant
