### ISSUE TITLE
Feat: Beweisbereich

### ISSUE THREAD

**Issue by JuliaSageder** [UniRegensburg/basisdokument#38]
**Beschreibung des Features**
Es soll möglich sein an einem Beitrag unten einen Beweis (nur Text) anzubringen, um zu verhindern, dass Nutzer Beweise in separaten Beiträgen anbringen (Nachverfolgung/Zugehörigkeitsproblem!). Realisierbar wäre das ganze am Besten in einer Art Footer, der ähnlich wie der Header als Balken farblich hinterlegt ist und in dem man via Button einen neuen Beweis hinzufügen kann. Es soll außerdem bei Tippen des neuen Beweises (vgl. z.B. Lesezeichennamensvergabe, Standardüberschriften o.ä. Interaktionen) eine Liste der bereits im Dokument vergebenen Beweise in einem Dropdown vorgeschlagen werden, um Tippfehler zu vermeiden.

**Akzeptanzkriterien**
- [x] Footer zu Beiträgen hinzufügen
- [x] Button "Beweis hinzufügen" in den Footer integrieren
- [x] Namensvergabe + Dropdownliste für Beweise integrieren
- [x] Datenstruktur um Beweise erweitern
- [x] Beweise als eigene Zeile einer Beitragstabelle ins neue PDF integrieren

**Screenshots**
![image](https://user-images.githubusercontent.com/126691623/228765999-855f704d-8c4d-42f5-b802-8432602c92d8.png)

**Comment by JuliaSageder** [comment]
Update:
- [ ] "Anlagen" in "Beweisangebot" umbenennen
- [ ] tatsächliche Anlagen intern nummerieren: Der Kläger nummeriert normal K1, K2, usw. und der Beklagte B1, B2, usw.
z.B. 1. Kaufvertrag zwischen Max und Erika vom 09.05.2023 als Anlage K 1. || 2. Schreiben des Beklagten vom 09.04.2023 als Anlage K 2.
- [ ] nicht jedes Beweisangebot hat zwingend eine Anlage! -> Anlage *optional* zu jedem Beweis (Häkchen?)
z.B. 1. Zeugnis des Max Mustermann, zu laden über ... (Anschrift) || 2. Parteivernehmung der Erika Musterfrau

**Screenshot:**
![image](https://github.com/UniRegensburg/basisdokument/assets/126691623/eed4b2be-6f0b-4ba0-8c37-b981ea1f9e6f)

**Comment by tina-e** [comment]
### Löschen
- [ ] im Beitrag löschen ohne andere Referenz: Warnhinweis oder Wahlmöglichkeit? -> Diskussion
- [ ] wenn nach Warnhinweis gelöscht, dann KX-Nummerierung anpassen
- [ ] im Beitrag löschen mit anderer Referenz: Löschen aus Beitrag

### Verschieben
DnD-Verschiebung im Beitrag
- [ ] im Beitrag: Ändert KX-Nummerierung nicht

### Sidebar
Übersicht über alle existierenden Beweise
- [ ] Aufteilung in Parteien wie bei Notizen (mit/ohne Bezug)
- [ ] Klickbare Verlinkung von Beiträgen, die Beweise referenzieren
- [ ] Versionierung darstellen? / Löschen? Bearbeiten?

**Comment by JuliaSageder** [comment]
Neue Anpassungswünsche nach JourFixe:
- [ ] Anlagennummern sollen bei Bedarf manuell angepasst werden können (K1... passt bei 95% der Fälle, in seltenen Fällen sollte eine Umbenennung aber möglich sein)
- [ ] Liste der Beweise vorfiltern beim Tippen um Auswahl zu erleichtern
- [ ] Fehler bei den Beweisen im PDF aufgetreten (@JuliaSageder)

**Comment by JuliaSageder** [comment]
[ ] Fix für bereits bestehende Basisdokument Dateien (cannot read properties of undefined Fehler)
