### ISSUE TITLE
Bugfix: Keine Zuordnung von Edit- und Basisdok-Datei

### ISSUE THREAD

**Issue by JuliaSageder** [UniRegensburg/basisdokument#59]
**Describe the bug**
Lesezeichenlinks zu den Beiträgen fehlen

**To Reproduce**
1. Basisdokument öffnen
2. Auf den Lesezeichentab in der Sidebar klicken
3. Lesezeichenlinks zu den Beiträgen fehlen (s. Sreenshot)

**Expected behavior**
Lesezeichenlinks sollten nicht fehlen

**Screenshots**
![image](https://user-images.githubusercontent.com/126691623/233927228-8c936247-ed7e-425c-bc52-cbb35ed18842.png)

**Comment by JuliaSageder** [comment]
Nutzerfehler: Falsche Bearbeitungsdatei zum Basisdokument hochgeladen! -> Möglichkeit das vom System zu prüfen?

**Comment by JuliaSageder** [comment]
![image](https://github.com/UniRegensburg/basisdokument/assets/126691623/f7d60afe-cc4d-4390-8f9d-740a2d67dc23)

Kleiner Fehler beim Testen: pdf wird nicht mehr korrekt abgefangen

**Comment by tina-e** [comment]
> ![image](https://user-images.githubusercontent.com/126691623/255834063-f7d60afe-cc4d-4390-8f9d-740a2d67dc23.png)
> 
> Kleiner Fehler beim Testen: pdf wird nicht mehr korrekt abgefangen

fixed 👍🏼
