### ISSUE TITLE
Feat: Mandantendomain

### ISSUE THREAD

**Issue by JuliaSageder** [UniRegensburg/basisdokument#60]
**Beschreibung des Features**
Die readonly-Funktion für Mandant:innen soll eine eigene Domain bekommen: mandant.parteivortrag.de, die eine einfacher aufgebaute Auth-Seite besitzt (nur Drag + Drop/evtl. als Alternative "Hochladen" wie in vergleichbaren Interaktionsmöglichkeiten, aber keine Rollen und keine Interaktionsart).

**Akzeptanzkriterien**
- [x] eigene Domain mandant.parteivortrag.de einrichten
- [ ] eigenen branch für die domain einrichten z.B. "readonly"
- [ ] eigene DIR_READONLY auf dem Server einrichten + SSL Zertifikat checken
- [x] eigene workflow_readonly.yaml anlegen und einrichten
- [x] eigene/abgeänderte Auth-Seite für die domain

**Comment by tina-e** [comment]
> **Beschreibung des Features** Die readonly-Funktion für Mandant:innen soll eine eigene Domain bekommen: mandant.parteivortrag.de, die eine einfacher aufgebaute Auth-Seite besitzt (nur Drag + Drop/evtl. als Alternative "Hochladen" wie in vergleichbaren Interaktionsmöglichkeiten, aber keine Rollen und keine Interaktionsart).
> 
> **Akzeptanzkriterien**
> 
> * [x]  eigene Domain mandant.parteivortrag.de einrichten
> * [ ]  ~~eigenen branch für die domain einrichten z.B. "readonly"~~
> * [ ]  eigene **WORK_DIR_READONLY** auf dem Server einrichten + SSL Zertifikat checken
> * [x]  eigene workflow_readonly.yaml anlegen und einrichten
> * [x]  eigene/abgeänderte Auth-Seite für die domain

+GitHub Secret `WORK_DIR_READONLY` anlegen!
